package hue;

import java.util.Map;

/**
 * Sample usage of the Philips Hue API.
 *
 * @author <a href="mailto:luigi.derussis@uniupo.it">Luigi De Russis</a>
 * @version 1.0 (18/05/2017)
 */
public class Hue
{
	// the URL of the Philips Hue bridge
	private static String baseURL = "http://172.30.1.138";

    // example username, generated by following https://www.developers.meethue.com/documentation/getting-started
    private static String username = "lqo778nsVu54Kb1mSLa6pyIGPysfxYzQdt5litQR";

    // base URL for lights
    private static String lightsURL = baseURL + "/api/" + username + "/lights/";
    
    private static Map<String, ?> allLights;
    

    private static void init()
    {
    	// get the Hue lamps
    	allLights = Rest.get(lightsURL);
    }
    
	//GLI SI DOVRà PASSARE COME PARAMETRO IL USERNAME TOKEN?
    public static void lightsOn() throws HueException 
    {
    	init();

        // prende la prima lampadina e accende
		if (allLights.containsKey("1")) 
		{
			String callURL = lightsURL + "1" + "/state";
			String body = "{ \"on\" : true}";
			Rest.put(callURL, body, "application/json");
		}
		else
			throw new HueException("No lights found!");
    }
    public static void lightsOff() throws HueException 
    {
    	init();

        // prende la prima lampadina e accende
		if (allLights.containsKey("1")) 
		{
			String callURL = lightsURL + "1" + "/state";
			String body = "{ \"on\" : false}";
			Rest.put(callURL, body, "application/json");
		}
		else
			throw new HueException("No lights found!");
    }
}